import { beforeEach, describe, expect, it, vi } from "vitest";

const UUIDS = {
  appUser: "11111111-1111-4111-8111-111111111111", attachment: "22222222-2222-4222-8222-222222222222",
  conversation: "33333333-3333-4333-8333-333333333333", attempt: "44444444-4444-4444-8444-444444444444",
  practice: "55555555-5555-4555-8555-555555555555", escalation: "66666666-6666-4666-8666-666666666666",
  unit: "77777777-7777-4777-8777-777777777777", content: "88888888-8888-4888-8888-888888888888",
};

const mocks = vi.hoisted(() => ({
  generateGeminiJson: vi.fn(), getOrCreateAppUser: vi.fn(), assertSupabaseAdmin: vi.fn(), consumeSolveQuota: vi.fn(), uploadMathPhoto: vi.fn(), getAttachmentForUser: vi.fn(), downloadMathPhoto: vi.fn(), updateAttachmentRecognition: vi.fn(), createConversation: vi.fn(), getConversationForUser: vi.fn(), createMathAttempt: vi.fn(), listRecentAttempts: vi.fn(), listPracticeHistory: vi.fn(), getAttemptForUser: vi.fn(), savePracticeResult: vi.fn(), createEscalation: vi.fn(), listEscalations: vi.fn(), updateEscalationStatus: vi.fn(), getTutorContext: vi.fn(), listTeacherUnits: vi.fn(), listTeacherContents: vi.fn(), upsertTeacherUnit: vi.fn(), addApprovedContent: vi.fn(),
}));

vi.mock("../tutor/gemini", () => ({ GEMINI_TUTOR_MODEL: "gemini-3.6-flash", generateGeminiJson: mocks.generateGeminiJson }));
vi.mock("../tutor/supabaseDb", () => ({ getOrCreateAppUser: mocks.getOrCreateAppUser, assertSupabaseAdmin: mocks.assertSupabaseAdmin, consumeSolveQuota: mocks.consumeSolveQuota, uploadMathPhoto: mocks.uploadMathPhoto, getAttachmentForUser: mocks.getAttachmentForUser, downloadMathPhoto: mocks.downloadMathPhoto, updateAttachmentRecognition: mocks.updateAttachmentRecognition, createConversation: mocks.createConversation, getConversationForUser: mocks.getConversationForUser, createMathAttempt: mocks.createMathAttempt, listRecentAttempts: mocks.listRecentAttempts, listPracticeHistory: mocks.listPracticeHistory, getAttemptForUser: mocks.getAttemptForUser, savePracticeResult: mocks.savePracticeResult, createEscalation: mocks.createEscalation, listEscalations: mocks.listEscalations, updateEscalationStatus: mocks.updateEscalationStatus }));
vi.mock("../tutor/supabaseTeacherDb", () => ({ getTutorContext: mocks.getTutorContext, listTeacherUnits: mocks.listTeacherUnits, listTeacherContents: mocks.listTeacherContents, upsertTeacherUnit: mocks.upsertTeacherUnit, addApprovedContent: mocks.addApprovedContent }));

import { tutorRouter, validatePhotoDataUrl } from "./tutor";

const student = { id: 12, openId: "student-12", name: "Test Student", email: "student@example.com", loginMethod: "manus", role: "user" as const, createdAt: new Date(), updatedAt: new Date(), lastSignedIn: new Date() };
const readySolution = { status: "ready", confidence: 92, needsClarification: false, clarificationQuestion: "", problemRestatement: "解 3x - 7 = 11。", keyConcepts: ["等量公理"], steps: [{ title: "加回 7", reason: "等式兩邊同加 7", work: "3x = 18" }], verification: "代入 x = 6，原式成立。", commonMistakes: ["移項符號要改變"], errorTags: ["移項符號"], variationQuestion: "試試看：4x + 5 = 21。", safetyNote: "AI 可能出錯；重要答案請再次驗算。" };
const caller = () => tutorRouter.createCaller({ user: student } as never);
const adminCaller = () => tutorRouter.createCaller({ user: { ...student, role: "admin" as const } } as never);

beforeEach(() => {
  vi.clearAllMocks();
  mocks.getOrCreateAppUser.mockResolvedValue({ id: UUIDS.appUser, role: "student" }); mocks.assertSupabaseAdmin.mockResolvedValue({ id: UUIDS.appUser, role: "admin" }); mocks.consumeSolveQuota.mockResolvedValue({ allowed: true, remaining: 18 }); mocks.getTutorContext.mockResolvedValue({ rules: "先問學生已知條件。", contents: [] }); mocks.createConversation.mockResolvedValue(UUIDS.conversation); mocks.createMathAttempt.mockResolvedValue(UUIDS.attempt); mocks.generateGeminiJson.mockResolvedValue(JSON.stringify(readySolution));
  mocks.getAttemptForUser.mockResolvedValue(UUIDS.attempt);
  mocks.getConversationForUser.mockResolvedValue(UUIDS.conversation);
});

describe("Supabase 國中數學解題路由", () => {
  it("接受安全圖片資料並拒絕格式偽裝", () => { expect(validatePhotoDataUrl("data:image/png;base64,aGVsbG8=", "image/png").toString()).toBe("hello"); expect(() => validatePhotoDataUrl("data:image/gif;base64,aGVsbG8=", "image/png")).toThrow("JPEG、PNG 或 WebP"); });
  it("在沒有題目或照片時拒絕模型呼叫", async () => { await expect(caller().solve({ question: "", grade: "seven", unitKey: "linear-equations", mode: "guided" })).rejects.toThrow("請輸入題目"); expect(mocks.generateGeminiJson).not.toHaveBeenCalled(); });
  it("以 Supabase UUID 保存對話與結構化解題", async () => { const result = await caller().solve({ question: "3x - 7 = 11", grade: "seven", unitKey: "linear-equations", mode: "step_by_step" }); expect(mocks.getOrCreateAppUser).toHaveBeenCalledWith(student); expect(mocks.createConversation).toHaveBeenCalledWith(expect.objectContaining({ userId: UUIDS.appUser })); expect(mocks.createMathAttempt).toHaveBeenCalledWith(expect.objectContaining({ userId: UUIDS.appUser, conversationId: UUIDS.conversation })); expect(result).toMatchObject({ attemptId: UUIDS.attempt, conversationId: UUIDS.conversation, remaining: 18 }); });
  it("把題目照片上傳與附件參照交由 Supabase Storage", async () => { mocks.uploadMathPhoto.mockResolvedValue({ attachmentId: UUIDS.attachment, storagePath: `${UUIDS.appUser}/q.png` }); const result = await caller().uploadPhoto({ filename: "題目.png", mimeType: "image/png", dataUrl: "data:image/png;base64,aGVsbG8=" }); expect(mocks.uploadMathPhoto).toHaveBeenCalledWith(expect.objectContaining({ userId: UUIDS.appUser, bytes: expect.any(Buffer) })); expect(result).toEqual({ attachmentId: UUIDS.attachment, recognitionStatus: "pending" }); });
  it("讀取私有照片位元組，低信心時標示需補拍", async () => { mocks.getAttachmentForUser.mockResolvedValue({ id: UUIDS.attachment, storagePath: "private/photo.png", mimeType: "image/png" }); mocks.downloadMathPhoto.mockResolvedValue({ data: "aGVsbG8=", mimeType: "image/png" }); mocks.generateGeminiJson.mockResolvedValue(JSON.stringify({ isReadable: false, confidence: 40, transcription: "2x + [不清楚]", clarification: "請補拍。", cropHint: "保留等號。" })); const result = await caller().recognizePhoto({ attachmentId: UUIDS.attachment }); expect(mocks.downloadMathPhoto).toHaveBeenCalledWith("private/photo.png", "image/png"); expect(mocks.updateAttachmentRecognition).toHaveBeenCalledWith(UUIDS.attachment, "unclear"); expect(result.isReadable).toBe(false); });
  it("不允許學生 A 讀取或引用學生 B 的私有附件、解題、練習與案件", async () => { const studentB = { ...student, id: 13, openId: "student-13", email: "student-b@example.com" }; const otherId = "99999999-9999-4999-8999-999999999999"; mocks.getOrCreateAppUser.mockImplementation(async (user: { id: number }) => ({ id: user.id === 12 ? UUIDS.appUser : otherId, role: "student" })); mocks.getAttachmentForUser.mockResolvedValue(undefined); mocks.getAttemptForUser.mockResolvedValue(undefined); const studentBCaller = tutorRouter.createCaller({ user: studentB } as never); await expect(studentBCaller.recognizePhoto({ attachmentId: UUIDS.attachment })).rejects.toThrow("找不到這張題目照片"); await expect(studentBCaller.savePractice({ sourceAttemptId: UUIDS.attempt, question: "他人的題目", status: "incorrect" })).rejects.toThrow("找不到這筆解題紀錄"); await expect(studentBCaller.reportConcern({ attemptId: UUIDS.attempt, reason: "wrong_answer" })).rejects.toThrow("找不到這筆解題紀錄"); expect(mocks.downloadMathPhoto).not.toHaveBeenCalled(); expect(mocks.savePracticeResult).not.toHaveBeenCalled(); expect(mocks.createEscalation).not.toHaveBeenCalled(); });
  it("不允許學生 A 以學生 B 的 conversationId 延續解題", async () => { const studentB = { ...student, id: 13, openId: "student-13", email: "student-b@example.com" }; mocks.getConversationForUser.mockResolvedValue(undefined); await expect(tutorRouter.createCaller({ user: studentB } as never).solve({ question: "x + 2 = 8", grade: "seven", unitKey: "linear-equations", mode: "guided", conversationId: UUIDS.conversation })).rejects.toThrow("找不到這個解題對話"); expect(mocks.generateGeminiJson).not.toHaveBeenCalled(); expect(mocks.createMathAttempt).not.toHaveBeenCalled(); });
  it("保存變式練習與教師協助案件至 Supabase", async () => { mocks.savePracticeResult.mockResolvedValue(UUIDS.practice); mocks.createEscalation.mockResolvedValue(UUIDS.escalation); await expect(caller().savePractice({ sourceAttemptId: UUIDS.attempt, question: "4x + 5 = 21", studentAnswer: "x=4", status: "correct" })).resolves.toBe(UUIDS.practice); await expect(caller().reportConcern({ attemptId: UUIDS.attempt, reason: "teacher_help" })).resolves.toEqual({ escalationId: UUIDS.escalation, notified: false }); expect(mocks.createEscalation).toHaveBeenCalledWith(expect.objectContaining({ userId: UUIDS.appUser, attemptId: UUIDS.attempt, notificationDelivered: false })); });
  it("管理者讀取與更新 Supabase 教師資料，非管理者會被拒絕", async () => { mocks.listTeacherUnits.mockResolvedValue([{ id: UUIDS.unit }]); mocks.listTeacherContents.mockResolvedValue([{ id: UUIDS.content }]); mocks.listEscalations.mockResolvedValue([{ id: UUIDS.escalation }]); const admin = adminCaller(); await expect(admin.teacher.listUnits()).resolves.toHaveLength(1); await expect(admin.teacher.listContents()).resolves.toHaveLength(1); await expect(admin.teacher.listEscalations()).resolves.toHaveLength(1); await expect(admin.teacher.updateEscalationStatus({ id: UUIDS.escalation, status: "resolved" })).resolves.toBeUndefined(); expect(mocks.assertSupabaseAdmin).toHaveBeenCalled(); await expect(caller().teacher.listUnits()).rejects.toThrow(); });
});
